#!/bin/bash

# Variable for testing; default is 1
MOVE_BACK=1
PI_TESTS=1

# Make a directory for the student written tests to move into
mkdir ./student-tests

# Move the student written tests into the newly created directory
mv ./src/test/java/calendar/*.java ./student-tests

# Move the evosuite best tests into the test folder
mvn evosuite:export

# Run the tests generated by evosuite.
mvn test > evotests.log

if [ $PI_TESTS -eq 1 ]
then
    printf "\n\nPaused for 20 seconds for result viewing...\n\n"
    #sleep 20
    printf "Starting Pitest...\n\n"
    sleep 2
    mvn org.pitest:pitest-maven:mutationCoverage > pitest.log 2>&1

    printf "\n\nPaused for 20 seconds for result viewing...\n\n"
    #sleep 20
fi
    
if [ $MOVE_BACK -eq 1 ]
then
    # Remove the EvoSuite Tests from the test directory
    rm -rf ./src/test/java/calendar/*ESTest*

    # Move the student written tests back to the test folder
    # and remove the student tests folder 
    mv ./student-tests/*.java ./src/test/java/calendar/
    rm -rf ./student-tests

    printf "\n\nEvoSuite tests removed from test directory,\n"
    printf "and student tests moved back.\n\n"
fi

exit 0